devtools::install_github("noerw/opensensmapr")
install.packages("here")
install.packages("dggridR")
install.packages("gridExtra")
install.packages("rgeos")
install.packages("dplyr")
install.packages("sf")
install.packages("ggplot2")
system("pip3 install --upgrade wheel")
system("pip3 install ipyrmd")
