install.packages("tidyverse")
install.packages("here")
install.packages("gridExtra")
install.packages("rgeos")
install.packages("dplyr")
install.packages("sf")
install.packages("ggplot2")
install.packages("dggridR")
system("pip3 install --upgrade wheel")
system("pip3 install ipyrmd")
